version: '2'
services:
  awep:
    build: .
    ports:
      - "9000:9000"
    networks:
      - awep
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - awep
networks:
  awep:
volumes:
  db-data:
